sudo: required
dist: trusty
services:
- docker
env:
  global:
  - COMMIT_AUTHOR_EMAIL=skynet@open.qa
  matrix:
  - DOCKERFILE=direct_tests
  - DOCKERFILE=direct_tests_ui
  - DOCKERFILE-direct_testfull_stack
  - DOCKERFILE-direct_test05-scheduler_full
  - DOCKERFILE-direct_test33-developer_mode
before_script:
- docker pull anikitinsuse/openqabuildcache:latest
cache:
  directories:
  - assets/cache
script:
- docker run -f docker/${DOCKERFILE}.Dockerfile --cache-from anikitinsuse/openqabuildcache:latest
