sudo: required
dist: trusty
services:
- docker
env:
  global:
  - COMMIT_AUTHOR_EMAIL=skynet@open.qa
  matrix:
  - DOCKERFILE=direct_tests
  - DOCKERFILE=direct_tests_ui
  - DOCKERFILE=direct_testfull-stack
  - DOCKERFILE=direct_test05-scheduler-full
  - DOCKERFILE=direct_test33-developer_mode
before_script:
- docker pull registry.opensuse.org/devel/openqa/containers/openqa_dev:latest
script:
- make direct-test-dockerfiles
- docker build -f docker/${DOCKERFILE}.Dockerfile .
